version: "3.8"

services:
  backend:
    build: ./blog-backend
    container_name: blog-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://root:root@express.silay2q.mongodb.net/blogger?retryWrites=true&w=majority&appName=express
    networks:
      - blog-network

  frontend:
    build: ./blog-ui
    container_name: blog-ui
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
